import { defineField, defineType } from 'sanity';

export default defineType({
  name: 'project',
  title: 'Project',
  type: 'document',
  fields: [
    defineField({
      name: 'title',
      title: 'Project Name',
      type: 'string',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: { source: 'title' },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'industry',
      title: 'Industry',
      type: 'string',
      options: {
        list: [
          'Apartments',
          'Commercial',
          'Hospitality',
          'Mixed Development',
          'Residential',
          'Civil Works',
          'Industrial',
          'Townhouses',
          'Institutional',
          'Infrastructure',
          'Churches',
          'Factories',
          'Warehouses',
          'Renovations',
          'Structural Assessments',
        ],
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'clientSector',
      title: 'Client / Sector',
      type: 'string',
      description: 'Example: Residential developer, hospitality client, institution, industrial client.',
    }),
    defineField({
      name: 'location',
      title: 'Location',
      type: 'string',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'year',
      title: 'Year',
      type: 'string',
      description: 'Use a year such as 2025, or leave as "To be specified".',
    }),
    defineField({
      name: 'status',
      title: 'Year / Status',
      type: 'string',
      description: 'Example: Completed 2025, Ongoing, Design stage, Construction stage.',
    }),
    defineField({
      name: 'summary',
      title: 'Short Summary',
      type: 'text',
      rows: 3,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'fullDescription',
      title: 'Full Description',
      type: 'text',
      rows: 5,
    }),
    defineField({
      name: 'masfyScope',
      title: 'Masfy Scope',
      type: 'text',
      rows: 4,
      description: 'Describe Masfy’s role, such as structural design, civil design, coordination, or technical input.',
    }),
    defineField({
      name: 'systems',
      title: 'Structural / Civil Systems',
      type: 'array',
      of: [{ type: 'string' }],
      description: 'Example: reinforced concrete frame, foundations, drainage, retaining walls.',
    }),
    defineField({
      name: 'services',
      title: 'Services Provided',
      type: 'array',
      of: [{ type: 'string' }],
    }),
    defineField({
      name: 'challenges',
      title: 'Challenges',
      type: 'text',
      rows: 4,
    }),
    defineField({
      name: 'solution',
      title: 'Engineering Solution',
      type: 'text',
      rows: 4,
    }),
    defineField({
      name: 'outcome',
      title: 'Outcome',
      type: 'text',
      rows: 4,
    }),
    defineField({
      name: 'featuredImage',
      title: 'Main Project Image',
      type: 'image',
      options: { hotspot: true },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'gallery',
      title: 'Gallery Images',
      type: 'array',
      of: [{ type: 'image', options: { hotspot: true } }],
    }),
    defineField({
      name: 'featured',
      title: 'Show on Homepage',
      type: 'boolean',
      initialValue: true,
    }),
    defineField({
      name: 'order',
      title: 'Display Order',
      type: 'number',
      initialValue: 0,
    }),
  ],
  orderings: [
    {
      title: 'Display order',
      name: 'displayOrder',
      by: [{ field: 'order', direction: 'asc' }],
    },
  ],
  preview: {
    select: {
      title: 'title',
      subtitle: 'industry',
      media: 'featuredImage',
    },
  },
});
